services:
  backend:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - telco-network

  frontend:
    image: python:3.11-slim
    ports:
      - "8050:8050"
    volumes:
      - ./dashboard:/app/dashboard
    working_dir: /app/dashboard
    command: python -m http.server 8050
    networks:
      - telco-network
    depends_on:
      - backend

networks:
  telco-network:
    driver: bridge